# -*- coding: utf-8 -*-
"""
Created on Mon Apr  7 12:37:46 2025

@author: iant

FIND OCCULTATIONS CLOSEST TO EACH UTC TIME INPUT

THE ORBITLIST NEEDS TO BE GENERATED BY RUN_PLANNING FIRST
"""

from datetime import datetime, timedelta


search_for = "occultation"

list_types = ["NOMAD"]
# list_types = ["NOMAD", "ACS", "N/A"]

search_times = [
    # "2025 JUN 12 00:02:45",
    # "2025 JUN 12 21:40:06",
    # "2025 JUN 12 23:38:00",
    # "2025 JUN 13 23:13:14",
    # "2025 JUN 14 01:11:09",
    # "2025 JUN 14 22:48:25",
    # "2025 JUN 15 00:46:19",
    # "2025 JUN 16 00:21:29",
    # "2025 JUN 16 23:56:35",
    # "2025 JUN 17 01:54:29",
    # "2025 JUN 17 23:31:40",
    # "2025 JUN 18 01:29:33",
    # "2025 JUN 19 01:04:34",
    # "2025 JUN 19 03:02:59",
    # "2025 JUN 20 00:39:33",
    # "2025 JUN 20 02:37:26",
    # "2025 JUN 21 00:14:31",
    # "2025 JUN 21 02:12:23",
    # "2025 JUN 22 01:47:18",
    # "2025 JUN 22 03:45:23",
    # "2025 JUN 23 01:22:12",
    # "2025 JUN 23 03:20:04",
    # "2025 JUN 24 00:57:02",
    # "2025 JUN 24 02:54:54",
    # "2025 JUN 25 02:29:42",
    # "2025 JUN 25 04:27:52",
    # "2025 JUN 26 02:04:25",
    # "2025 JUN 26 04:02:17",
    # "2025 JUN 27 01:39:06",
    # "2025 JUN 27 03:36:57",
    # "2025 JUN 28 03:11:33",
    # "2025 JUN 28 05:09:23",
    # "2025 JUN 29 02:46:04",
    # "2025 JUN 29 04:43:54",
    # "2025 JUN 30 02:20:31",
    # "2025 JUN 30 04:18:21",
    # "2025 JUL 01 03:52:42",
    # "2025 JUL 01 05:50:31",
    # "2025 JUL 02 03:26:57",
    # "2025 JUL 02 05:24:46",
    # "2025 JUL 03 04:58:51",
    # "2025 JUL 03 06:57:23",
    # "2025 JUL 04 04:32:46",
    # "2025 JUL 04 06:30:33",
    # "2025 JUL 31 07:42:56",
    # "2025 AUG 01 07:16:39",
    # "2025 AUG 01 09:14:26",
    # "2025 AUG 02 06:50:36",
    # "2025 AUG 02 08:48:24",

    "2025 SEP 27 16:07:02",
    "2025 SEP 27 20:03:01",
    "2025 SEP 28 17:41:08",
    "2025 SEP 28 21:37:04",
    "2025 SEP 29 15:19:07",
    "2025 SEP 29 19:15:08",
    "2025 SEP 29 23:11:02",
    "2025 SEP 30 16:53:01",
    "2025 SEP 30 20:48:59",
    "2025 Oct 01 18:26:49",
    "2025 Oct 01 22:22:44",
    "2025 Oct 02 20:00:32",
    "2025 Oct 02 23:56:24",
    "2025 Oct 03 21:34:08",
    "2025 Oct 04 01:30:00",
    "2025 Oct 04 19:11:48",
    "2025 Oct 07 23:52:09",
    "2025 Oct 08 03:47:59",
    "2025 Oct 09 01:25:29",
    "2025 Oct 09 05:21:19",
    "2025 Oct 10 02:58:45",
    "2025 Oct 10 06:54:37",
    "2025 Oct 11 04:31:59",
    "2025 Oct 11 08:27:53",
    "2025 Oct 12 02:09:23",
    "2025 Oct 12 06:05:12",
    "2025 Oct 12 10:01:08",
    "2025 Oct 13 03:42:33",
    "2025 Oct 13 07:38:23",
    "2025 Oct 13 11:34:21",
    "2025 Oct 14 05:15:42",
    "2025 Oct 14 09:11:35",
    "2025 Oct 14 13:07:32",
    "2025 Oct 15 06:48:50",
    "2025 Oct 15 10:44:45",
    "2025 Oct 15 14:40:40",
    "2025 Oct 16 08:21:57",
    "2025 Oct 16 12:17:53",
    "2025 Oct 17 09:55:02",
    "2025 Oct 17 13:50:59",
    "2025 Oct 17 19:44:39",
    "2025 Oct 17 23:40:36",
    "2025 Oct 18 11:28:06",
    "2025 Oct 18 15:24:01",
    "2025 Oct 18 21:17:42",
    "2025 Oct 19 01:13:38",
    "2025 Oct 19 13:01:09",
    "2025 Oct 19 16:57:02",
    "2025 Oct 19 22:50:44",
    "2025 Oct 20 02:46:39",
    "2025 Oct 20 14:34:10",
    "2025 Oct 20 18:29:59",
    "2025 Oct 21 16:07:10",
    "2025 Oct 21 20:02:55",
    "2025 Oct 22 17:40:07",
    "2025 Oct 22 21:35:51",
    "2025 Oct 23 15:17:12",
    "2025 Oct 23 19:13:02",
    "2025 Oct 23 23:08:48",
    "2025 Oct 24 16:50:09",
    "2025 Oct 24 20:45:55",
    "2025 Oct 25 18:23:02",
    "2025 Oct 25 22:18:45",
    "2025 Oct 26 19:55:52",
    "2025 Oct 26 23:51:35",
    "2025 Oct 27 17:32:51",
    "2025 Oct 27 21:28:38",
    "2025 Oct 28 01:24:25",
]


SEARCH_DT_FORMAT = "%Y %b %d %H:%M:%S"


ORBITLIST_DT_FORMAT = "%Y %b %d %H:%M:%S"

for search_time in search_times:

    etTime = datetime.strptime(search_time, SEARCH_DT_FORMAT)

    found = False

    for orbit in orbitList:

        if "ingress" in orbit.keys():
            utcStart = orbit["ingress"]["utcStart"]
            utcEnd = orbit["ingress"]["utcEnd"]

            etStart = datetime.strptime(utcStart, ORBITLIST_DT_FORMAT) - timedelta(seconds=10)
            etEnd = datetime.strptime(utcEnd, ORBITLIST_DT_FORMAT) + timedelta(seconds=10)

            found = True
            if etStart < etTime and etTime < etEnd:
                orbitNumber = orbit["orbitNumber"]
                prime = orbit["ingress"]["primeInstrument"]
                if prime in list_types:
                    print("Match found: %s ingress orbit %i (%s) - %i row in Excel" % (prime, orbitNumber, search_time, orbitNumber+1))

        if "egress" in orbit.keys():
            utcStart = orbit["egress"]["utcStart"]
            utcEnd = orbit["egress"]["utcEnd"]

            etStart = datetime.strptime(utcStart, ORBITLIST_DT_FORMAT) - timedelta(seconds=10)
            etEnd = datetime.strptime(utcEnd, ORBITLIST_DT_FORMAT) + timedelta(seconds=10)

            found = True
            if etStart < etTime and etTime < etEnd:
                orbitNumber = orbit["orbitNumber"]
                prime = orbit["egress"]["primeInstrument"]
                if prime in list_types:
                    print("Match found: %s egress orbit %i (%s) - %i row in Excel" % (prime, orbitNumber, search_time, orbitNumber+1))

    if not found:
        print("Not found: %s" % search_time)
