# -*- coding: utf-8 -*-
"""
Created on Mon Apr 27 12:13:02 2020

@author: iant
"""



"""see https://issues.cosmos.esa.int/exomarswiki/display/OE/Event+Names
These must be manually inserted into the SOC event file"""
NOMAD_INGRESS_START_CODES = ["NOMAD_OCCIN_START", "NOMAD_OCCIN_ST_START", "NOMAD_UVIS_OCCIN_START", "NOMAD_UV_OCCIN_ST_START"]
NOMAD_INGRESS_END_CODES = ["NOMAD_OCCIN_END", "NOMAD_OCCIN_ST_END", "NOMAD_UVIS_OCCIN_END", "NOMAD_UV_OCCIN_ST_END"]
NOMAD_EGRESS_START_CODES = ["NOMAD_OCCEG_START", "NOMAD_OCCEG_ST_START", "NOMAD_UVIS_OCCEG_START", "NOMAD_UV_OCCEG_ST_START"]
NOMAD_EGRESS_END_CODES = ["NOMAD_OCCEG_END", "NOMAD_OCCEG_ST_END", "NOMAD_UVIS_OCCEG_END", "NOMAD_UV_OCCEG_ST_END"]
NOMAD_MERGED_START_CODES = ["NOMAD_OCCME_START"]
NOMAD_MERGED_END_CODES = ["NOMAD_OCCME_END"]
NOMAD_GRAZING_START_CODES = ["NOMAD_OCCGR_START"]
NOMAD_GRAZING_END_CODES = ["NOMAD_OCCGR_END"]
NOMAD_LIMB_START_CODES = ["NOMAD_LIMB_START", "NOMAD_LIMB_DAY_START"]
NOMAD_LIMB_END_CODES = ["NOMAD_LIMB_END", "NOMAD_LIMB_DAY_END"]
NOMAD_NIGHT_LIMB_START_CODES = ["NOMAD_LIMB_NIGHT_START"]
NOMAD_NIGHT_LIMB_END_CODES = ["NOMAD_LIMB_NIGHT_END"]

"""Old list - new list for MTP008 onwards is below"""
#ACS_INGRESS_START_CODES = ["ACS_MIR_OCCIN_START", "ACS_NIR_OCCIN_RA_START", "ACS_TIRSUN_OCCIN_START"]
#ACS_INGRESS_END_CODES = ["ACS_MIR_OCCIN_END", "ACS_NIR_OCCIN_RA_END", "ACS_TIRSUN_OCCIN_END"]
#ACS_EGRESS_START_CODES = ["ACS_MIR_OCCEG_START", "ACS_NIR_OCCEG_RA_START", "ACS_TIRSUN_OCCEG_START"]
#ACS_EGRESS_END_CODES = ["ACS_MIR_OCCEG_END", "ACS_NIR_OCCEG_RA_END", "ACS_TIRSUN_OCCEG_END"]
#ACS_MERGED_START_CODES = ["ACS_MIR_OCCME_START", "ACS_NIR_OCCME_RA_START", "ACS_TIRSUN_OCCME_START"]
#ACS_MERGED_END_CODES = ["ACS_MIR_OCCME_END", "ACS_NIR_OCCME_RA_END", "ACS_TIRSUN_OCCME_END"]
#ACS_GRAZING_START_CODES = ["ACS_MIR_OCCGR_START", "ACS_NIR_OCCGR_RA_START", "ACS_TIRSUN_OCCGR_START"]
#ACS_GRAZING_END_CODES = ["ACS_MIR_OCCGR_END", "ACS_NIR_OCCGR_RA_END", "ACS_TIRSUN_OCCGR_END"]

ACS_INGRESS_START_CODES = ["ACS_MIR_OCCIN_ST_START", "ACS_MIR_OCCIN_START", "ACS_TIRSUN_OCCIN_START", "ACS_TIRSCA_OCCIN_START"]
ACS_INGRESS_END_CODES = ["ACS_MIR_OCCIN_ST_END", "ACS_MIR_OCCIN_END", "ACS_TIRSUN_OCCIN_END", "ACS_TIRSCA_OCCIN_END"]
ACS_EGRESS_START_CODES = ["ACS_MIR_OCCEG_ST_START", "ACS_MIR_OCCEG_START", "ACS_TIRSUN_OCCEG_START", "ACS_TIRSCA_OCCEG_START"]
ACS_EGRESS_END_CODES = ["ACS_MIR_OCCEG_ST_END", "ACS_MIR_OCCEG_END", "ACS_TIRSUN_OCCEG_END", "ACS_TIRSCA_OCCEG_END"]
ACS_MERGED_START_CODES = ["ACS_MIR_OCCME_START", "ACS_NIR_OCCME_START", "ACS_TIRSUN_OCCME_START", "ACS_TIRSCA_OCCME_START"]
ACS_MERGED_END_CODES = ["ACS_MIR_OCCME_END", "ACS_NIR_OCCME_END", "ACS_TIRSUN_OCCME_END", "ACS_TIRSCA_OCCME_END"]
ACS_GRAZING_START_CODES = ["ACS_MIR_OCCGR_START", "ACS_TIRSUN_OCCGR_START", "ACS_TIRSCA_OCCGR_START"]
ACS_GRAZING_END_CODES = ["ACS_MIR_OCCGR_END", "ACS_TIRSUN_OCCGR_END", "ACS_TIRSCA_OCCGR_END"]

TERMINATOR_D2N_CODES = ["EXMGEO_TD2N"]
TERMINATOR_N2D_CODES = ["EXMGEO_TN2D"]

NOMAD_SOLAR_CALIBRATION_START_CODES = ["NO_SO_LINESCAN_START", "NO_UVIS_LINESCAN_START", "NO_UVIS_LINESCAN1_START", "NO_UVIS_LINESCAN2_START", "NO_FREQSCAN_START"]
NOMAD_SOLAR_CALIBRATION_END_CODES = ["NO_SO_LINESCAN_END", "NO_UVIS_LINESCAN_END", "NO_UVIS_LINESCAN1_END", "NO_UVIS_LINESCAN2_END", "NO_FREQSCAN_END"]
ACS_SOLAR_CALIBRATION_START_CODES = ["ACS_LARGESCAN_START", "ACS_LINESCAN1_START", "ACS_LINESCAN2_START", "ACS_LINESCAN3_START", "ACS_LINESCAN4_START", "ACS_SUNSTARE_START"]
ACS_SOLAR_CALIBRATION_END_CODES = ["ACS_LARGESCAN_END", "ACS_LINESCAN1_END", "ACS_LINESCAN2_END", "ACS_LINESCAN3_END", "ACS_LINESCAN4_END", "ACS_SUNSTARE_END"]

